# Generated by Django 5.2.8 on 2025-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_num',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
