# Generated by Django 5.2.8 on 2025-11-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityInfo',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=500)),
                ('facility_name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=200)),
                ('addr2', models.CharField(max_length=200)),
                ('addr3', models.CharField(max_length=200)),
                ('homepage', models.CharField(blank=True, max_length=200, null=True)),
                ('tel', models.CharField(blank=True, max_length=200, null=True)),
                ('time_date', models.JSONField(blank=True, null=True)),
                ('etc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'facility_info',
            },
        ),
    ]
