# Generated by Django 5.2.8 on 2025-11-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facility'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facility',
            table='facility',
        ),
    ]
